export const GET_VIDEOS = "GET_VIDEOS";
export const SELECT_VIDEO = "SELECT_VIDEO";
export const SET_SEARCHED_TERM = "SET_SEARCHED_TERM";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const SET_PREV_PAGES_COUNT = "SET_PREV_PAGE_COUNT";
export const SELECT_LOGO = "SELECT_LOGO";
export const SELECT_BG_CLR = "SELECT_BG_CLR";
export const SELECT_BODY_CLR = "SELECT_BODY_CLR";
